#!/usr/bin/env bash
set -e

PID=/var/run/hermes/hermes.pid
LOG=/var/log/hermes/hermes.log
CHRUBY=/usr/local/bin/chruby-exec
RUBY=$(cat .ruby-version)

echo 'Updating codebase...'

$CHRUBY $RUBY -- bundle install --deployment
$CHRUBY $RUBY -- bundle exec rake db:migrate --trace

echo 'Restarting daemon...'

$CHRUBY $RUBY -- bundle exec ruby ./bin/hermes -k -P $PID -l $LOG
$CHRUBY $RUBY -- bundle exec ruby ./bin/hermes -d -P $PID -l $LOG
