#!/usr/bin/env bash
set -e

source /usr/local/share/chruby/chruby.sh
source /usr/local/share/chruby/auto.sh

PID=/var/run/hermes/hermes.pid
LOG=/var/log/hermes/hermes.log
RUBY=$(cat .ruby-version)

chruby $RUBY

echo 'Updating codebase...'

bundle install --deployment
bundle exec rake db:migrate --trace

echo 'Restarting daemon...'

bundle exec ruby ./bin/hermes -k -P $PID -l $LOG
bundle exec ruby ./bin/hermes -d -P $PID -l $LOG
